name: Keep Supabase Alive
on:
  schedule:
    - cron: '0 9 */4 * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -X GET \
          "https://fhmlkzvlnxoxefkjfdaf.supabase.co/rest/v1/clients?select=id&limit=1" \
          -H "apikey: sb_publishable_MGXALhIJ_7H_areh27H8CQ_9ActdvWr" \
          -H "Authorization: Bearer sb_publishable_MGXALhIJ_7H_areh27H8CQ_9ActdvWr"
